### ISSUE TITLE
コンパイル元のSCSSファイルが最新版ではないような気がします

### ISSUE THREAD

**Issue by maoh-hf** [meganehardcore/highflat_hp#1]
`main.scss`をコンパイルしても既存の`main.css`が吐き出されなかったので…。

Firefoxでのhoverの不具合修正のために一旦CSSを修正してみましたが、
SCSSを修正する術がなかったのでいずれ先祖返りしそうです😢 

今後のためにも、git上のSCSSも常に最新版にしておいた方がいいと思うので
ご確認いただけますか？

（個人的にすっごくムズムズするので、SCSSから直しておきたいです…😭）

**Comment by meganehardcore** [comment]
なるほど…確かにSCSSを修正しないとデグレする可能性は大いにありますね。
ちょいと嫁に確認してみます。ありがとうございます！

**Comment by maoh-hf** [comment]
よろしくお願いします 🙏

**Comment by meganehardcore** [comment]
本番環境に適用しました！
また、SCSSをプッシュしました。
対応ありがとうございました！

**Comment by maoh-hf** [comment]
@meganehardcore 
ありがとうございます！

すみません、先ほど、firefox環境ではメニューのhoverも動いていなかったことに気がついたので、
そちらもSCSSを修正してCSSをコンパイルしてPushしておきました。（プロフィール画面の修正も反映してあります）

お時間ある時に確認して反映していただけると嬉しいです😃
後から後からすみません、よろしくお願いいたします 🙏

**Comment by meganehardcore** [comment]
@maoh-hf 
対応遅れてすいませんでした。
細かいところまでありがとうございます！本番に適用させてもらいました！
